# Generated by Django 5.1.6 on 2025-03-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_donorresponse_is_select_blooddonationhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='donation_count',
            field=models.IntegerField(default=0),
        ),
    ]
