# Generated by Django 5.1.6 on 2025-04-13 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_donorresponse_is_saved_delete_accepteddonor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodinventory',
            name='available_units',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
