# Generated by Django 5.1.6 on 2025-04-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_bloodinventory_available_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodinventory',
            name='available_units',
            field=models.FloatField(),
        ),
    ]
